# Generated by Django 4.1.4 on 2023-01-15 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('email_address', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fo_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('email_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('su_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('phone_num', models.IntegerField()),
                ('email_address', models.CharField(max_length=100)),
            ],
        ),
    ]
