# Generated by Django 4.1.4 on 2023-01-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_id', models.CharField(max_length=10)),
                ('ship_to_date', models.DateField()),
                ('order_date', models.DateField()),
                ('ship_to_address', models.TextField()),
            ],
        ),
    ]
